language: java
jdk:
  - oraclejdk8

services:
  - mysql
  
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

before_install:
  - mysql -e 'CREATE DATABASE inglesapp;'
