language: java
jdk:
  - oraclejdk8

env:
  - DB=mysql db_dsn='mysql://root@127.0.0.1/inglesapp'

services:
  - mysql

before_install:
  - sudo service mysql stop || sudo service mysql-5.6 stop || sudo stop mysql-5.6 || sudo stop mysql || echo "failed to stop mysql"
  - sudo docker run -d -p 3306:3306 mysql:5.7
  - mysql -u root -e "CREATE DATABASE inglesapp;"
